feat: initi function that get token in env var

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,16 +1,37 @@
 #!/bin/env bash
+
+# Define the dependencies
+dependencies=("curl" "git" "jq" "go")
+
+# Array to track missing dependencies
+missing=()
+
+# Function to check if a dependency is installed
 need() {
-    if ! command -v "$1" &>/dev/null; then
-        if command -v pacman &>/dev/null; then
-            sudo pacman -Sy --needed --noconfirm "$1"
-        else
-            echo "install $1 with your distro pkgmanager"
-        fi
+    if ! command -v "$1" &> /dev/null
+    then
+        missing+=("$1")
     fi
 }
-need curl
-need git
-need jq
+
+# Loop through the dependencies and check each one
+for dependency in "${dependencies[@]}"
+do
+    need "$dependency"
+done
+
+# Check if there are any missing dependencies
+if [ ${#missing[@]} -ne 0 ]
+then
+    echo "The following dependencies are missing: ${missing[*]}"
+    echo "Please install the missing dependencies and try again."
+    exit 1
+else
+    echo "All dependencies are installed."
+fi
+
+# finish later
+
 git clone https://github.com/X3ric/octobot
 cd octobot
 chmod +x "./ghbot"
